title: Hello, world! I'm Flynn's Blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fenglinliu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Flynn Liu # add your name
author-img: flynn-liu.jpg # add your photo
about-author: I am a web developer focusing on devops and bigdata. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: fenglinliu # add your Github handle
social-linkedin: fenglinliu # add your Linkedin handle
social-email: liufenglin@163.com # add your Email address
social-weixin: qqtiandao_chouqin # add your weixin address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
